# Generated by Django 5.1.2 on 2025-01-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_Registro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
