# Generated by Django 5.1.2 on 2025-01-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_alter_usuario_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='puntuacion',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
